'use client';
import { useEffect, useState } from 'react';
const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api/v1';
type Summary = { contentVersion: string; questions: number; choices: number; tags: number; axes: number; eras: number; regions: number };
type Question = { id: string; stage: number; text: string; choiceCount: number };
type History = { contentVersion: string; published: number; digest: string; publishedAt: string };
export default function AdminHome() {
  const [summary, setSummary] = useState<Summary | null>(null); const [questions, setQuestions] = useState<Question[]>([]); const [history, setHistory] = useState<History[]>([]); const [drafts, setDrafts] = useState<Record<string, string>>({}); const [message, setMessage] = useState('');
  const load = async () => { const [s, q, h] = await Promise.all([fetch(`${API}/admin/content/summary`).then((r) => r.json()), fetch(`${API}/admin/content/questions`).then((r) => r.json()), fetch(`${API}/admin/content/publish-history`).then((r) => r.json())]); setSummary(s); setQuestions(q.items); setHistory(h.items); };
  useEffect(() => { void load(); }, []);
  const publish = async () => { const result = await fetch(`${API}/admin/content/publish`, { method: 'POST' }).then((r) => r.json()); setMessage(`publish 완료: ${result.published}건 / ${result.contentVersion}`); };
  const saveDraft = async (q: Question) => { const text = drafts[q.id]; if (!text?.trim()) return; await fetch(`${API}/admin/content/questions/${q.id}/draft`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }); setMessage(`${q.id} 초안 저장 완료`); };
  return <main style={{ maxWidth: 1100, margin: '0 auto', padding: 32, fontFamily: 'sans-serif' }}><h1>전생록 콘텐츠 관리자</h1><p>콘텐츠 검수 및 publish 콘솔</p>{summary && <section style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12 }}>{[['버전', summary.contentVersion], ['질문', summary.questions], ['선택지', summary.choices], ['태그/축', `${summary.tags}/${summary.axes}`]].map(([label, value]) => <div key={label} style={{ border: '1px solid #ddd', borderRadius: 8, padding: 16 }}><small>{label}</small><strong style={{ display: 'block', fontSize: 24 }}>{value}</strong></div>)}</section>}<div style={{ margin: '24px 0' }}><button onClick={() => void publish()} style={{ padding: '10px 18px', cursor: 'pointer' }}>초안 publish</button><button onClick={() => void load()} style={{ padding: '10px 18px', marginLeft: 8, cursor: 'pointer' }}>새로고침</button>{message && <span style={{ marginLeft: 12 }}>{message}</span>}</div><h2>질문 목록</h2><table style={{ width: '100%', borderCollapse: 'collapse' }}><thead><tr><th align="left">ID</th><th align="left">단계</th><th align="left">문구</th><th align="right">선택지</th><th>초안</th></tr></thead><tbody>{questions.map((q) => <tr key={q.id}><td style={{ borderTop: '1px solid #eee', padding: 8 }}>{q.id}</td><td style={{ borderTop: '1px solid #eee', padding: 8 }}>{q.stage}</td><td style={{ borderTop: '1px solid #eee', padding: 8 }}>{q.text}</td><td style={{ borderTop: '1px solid #eee', padding: 8 }} align="right">{q.choiceCount}</td><td style={{ borderTop: '1px solid #eee', padding: 8 }}><input aria-label={`${q.id} 초안`} value={drafts[q.id] ?? ''} placeholder="수정 문구" onChange={(e) => setDrafts((current) => ({ ...current, [q.id]: e.target.value }))} style={{ width: 220, padding: 6 }} /><button onClick={() => void saveDraft(q)} style={{ marginLeft: 6 }}>저장</button></td></tr>)}</tbody></table></main>;
}
