import type { HistoricalOccupation } from './types.js';

const allHistoricalOccupations: readonly HistoricalOccupation[] = [
  // v2.5 compatibility records: archived ResultCore documents retain these IDs.
  { id: 'OCC_01', label: '서기관', classId: 'CLASS_SCHOLAR', affinityTags: ['knowledge', 'stability'], dailyActions: ['기록을 정리했습니다', '봉인과 수량을 확인했습니다'], signatureObjects: ['갈대 첨필', '장부'] },
  { id: 'OCC_02', label: '기록 교사', classId: 'CLASS_RELIGIOUS', affinityTags: ['honor', 'courage'], dailyActions: ['글을 가르쳤습니다', '필사본을 교정했습니다'], signatureObjects: ['필사본', '먹그릇'] },
  { id: 'OCC_03', label: '의례 담당자', classId: 'CLASS_MILITARY', affinityTags: ['devotion', 'protection'], dailyActions: ['의례를 준비했습니다', '공동체의 순서를 알렸습니다'], signatureObjects: ['향 그릇', '방울'] },
  { id: 'OCC_04', label: '지도 제작자', classId: 'CLASS_MERCHANT', affinityTags: ['creativity', 'achievement'], dailyActions: ['길과 표식을 기록했습니다', '거리 정보를 대조했습니다'], signatureObjects: ['지도', '자'] },
  { id: 'OCC_05', label: '항해사', classId: 'CLASS_ARTISAN', affinityTags: ['adventure', 'freedom'], dailyActions: ['항로를 살폈습니다', '바람과 별을 기록했습니다'], signatureObjects: ['매듭줄', '방향판'] },
  { id: 'OCC_06', label: '공방 기술자', classId: 'CLASS_AGRICULTURE', affinityTags: ['achievement', 'survival'], dailyActions: ['도구를 손질했습니다', '재료를 나누었습니다'], signatureObjects: ['망치', '숫돌'] },
  { id: 'OCC_07', label: '공동체 돌봄 담당자', classId: 'CLASS_ARTIST', affinityTags: ['connection', 'empathy'], dailyActions: ['아픈 사람을 살폈습니다', '식량과 약재를 나누었습니다'], signatureObjects: ['약절구', '천 붕대'] },
  { id: 'OCC_08', label: '별과 바람을 읽는 길잡이', classId: 'CLASS_EXPLORER', affinityTags: ['spirituality', 'calm'], dailyActions: ['날씨를 읽었습니다', '안전한 길을 안내했습니다'], signatureObjects: ['지팡이', '매듭줄'] },
  { id: 'OCC_SCRIBE', label: '서기관', classId: 'CLASS_SCHOLAR', affinityTags: ['knowledge', 'stability'], dailyActions: ['점토판이나 종이에 수량과 이름을 기록했습니다', '기록을 대조해 누락과 오류를 바로잡았습니다'], signatureObjects: ['갈대 첨필', '봉인 인장'] },
  { id: 'OCC_MERCHANT', label: '교역 상인', classId: 'CLASS_MERCHANT', affinityTags: ['achievement', 'adventure'], dailyActions: ['화물의 무게와 값을 흥정했습니다', '외지 상인의 신용과 도착 소식을 확인했습니다'], signatureObjects: ['저울추', '매듭 장부'] },
  { id: 'OCC_CEREMONIAL', label: '의례 담당자', classId: 'CLASS_RELIGIOUS', affinityTags: ['spirituality', 'devotion'], dailyActions: ['달력에 맞춰 제물과 향을 준비했습니다', '공동체가 외우는 노래와 절차를 이끌었습니다'], signatureObjects: ['향 그릇', '의례 방울'] },
  { id: 'OCC_HEALER', label: '치유사', classId: 'CLASS_HEALER', affinityTags: ['empathy', 'protection'], dailyActions: ['환자의 열과 상처를 살폈습니다', '약재를 말리고 분량을 나누었습니다'], signatureObjects: ['약절구', '천 붕대'] },
  { id: 'OCC_FARMER', label: '농경 생산자', classId: 'CLASS_AGRICULTURE', affinityTags: ['stability', 'survival'], dailyActions: ['물길과 밭의 상태를 확인했습니다', '씨앗과 수확물을 가족 단위로 나누었습니다'], signatureObjects: ['괭이', '곡물 바구니'] },
  { id: 'OCC_ARTISAN', label: '공방 장인', classId: 'CLASS_ARTISAN', affinityTags: ['creativity', 'achievement'], dailyActions: ['재료의 결함을 골라내고 도구를 손질했습니다', '견습생에게 공정 순서를 보여 주었습니다'], signatureObjects: ['망치', '숫돌'] },
  { id: 'OCC_TEXTILE', label: '직물 장인', classId: 'CLASS_ARTISAN', affinityTags: ['creativity', 'stability'], dailyActions: ['실의 굵기와 염색 상태를 확인했습니다', '무늬의 순서를 세며 베를 짰습니다'], signatureObjects: ['북', '실패'] },
  { id: 'OCC_NAVIGATOR', label: '항해 길잡이', classId: 'CLASS_EXPLORER', affinityTags: ['adventure', 'knowledge'], dailyActions: ['별과 바람의 변화를 읽었습니다', '해안 표식과 항로를 동료에게 설명했습니다'], signatureObjects: ['매듭줄', '목제 방향판'] },
  { id: 'OCC_SHIPWRIGHT', label: '선박 목수', classId: 'CLASS_ARTISAN', affinityTags: ['creativity', 'protection'], dailyActions: ['배의 이음새와 누수를 점검했습니다', '목재를 다듬고 밧줄의 장력을 맞췄습니다'], signatureObjects: ['끌', '송곳'] },
  { id: 'OCC_TEACHER', label: '기록 교사', classId: 'CLASS_SCHOLAR', affinityTags: ['knowledge', 'empathy'], dailyActions: ['학생이 베낀 글과 계산을 교정했습니다', '읽을 자료와 필사 순서를 정했습니다'], signatureObjects: ['필사본', '먹그릇'] },
  { id: 'OCC_OFFICIAL', label: '하급 행정관', classId: 'CLASS_ADMIN', affinityTags: ['honor', 'stability'], dailyActions: ['청원과 세금 기록을 분류했습니다', '명령을 마을과 시장에 전달했습니다'], signatureObjects: ['목패', '관인'] },
  { id: 'OCC_GUARD', label: '도시 수비대원', classId: 'CLASS_MILITARY', affinityTags: ['courage', 'protection'], dailyActions: ['성문과 창고의 교대 상태를 확인했습니다', '통행 표식과 야간 등불을 점검했습니다'], signatureObjects: ['창', '등불'] },
  { id: 'OCC_BUILDER', label: '건축 기술자', classId: 'CLASS_ARTISAN', affinityTags: ['achievement', 'knowledge'], dailyActions: ['벽과 기둥의 수평을 확인했습니다', '돌과 목재의 사용량을 계산했습니다'], signatureObjects: ['먹줄', '나무 자'] },
  { id: 'OCC_MESSENGER', label: '전령과 길 안내인', classId: 'CLASS_COMMON_LABOR', affinityTags: ['freedom', 'courage'], dailyActions: ['목적지까지 안전한 길과 숙소를 확인했습니다', '봉인된 소식과 작은 화물을 전달했습니다'], signatureObjects: ['봉인 주머니', '지팡이'] },
  { id: 'OCC_FISHER', label: '어로 종사자', classId: 'CLASS_AGRICULTURE', affinityTags: ['survival', 'calm'], dailyActions: ['물때와 그물의 손상을 살폈습니다', '잡은 것을 소금에 절이거나 시장에 나눴습니다'], signatureObjects: ['그물추', '바구니'] },
  { id: 'OCC_PRINTER', label: '인쇄·책방 종사자', classId: 'CLASS_ARTISAN', affinityTags: ['knowledge', 'creativity'], dailyActions: ['글자판과 종이 상태를 확인했습니다', '찍힌 글의 번짐과 누락을 교정했습니다'], signatureObjects: ['목판', '잉크 솔'] },
  { id: 'OCC_FACTORY_WORKER', label: '공장 노동자', classId: 'CLASS_COMMON_LABOR', affinityTags: ['achievement', 'survival'], dailyActions: ['교대 시간에 맞춰 기계와 원료를 점검했습니다', '동료들과 작업 속도와 안전 수칙을 맞췄습니다'], signatureObjects: ['작업 장갑', '출근 카드'] },
  { id: 'OCC_NURSE', label: '간호사', classId: 'CLASS_HEALER', affinityTags: ['empathy', 'protection'], dailyActions: ['환자의 체온과 약 시간을 기록했습니다', '불안한 가족에게 치료 과정을 설명했습니다'], signatureObjects: ['청진기', '간호 기록지'] },
  { id: 'OCC_JOURNALIST', label: '신문 기자', classId: 'CLASS_SCHOLAR', affinityTags: ['knowledge', 'courage'], dailyActions: ['거리의 증언과 문서를 대조했습니다', '마감 전에 사실과 이름을 다시 확인했습니다'], signatureObjects: ['수첩', '휴대용 타자기'] },
  { id: 'OCC_RADIO_TECHNICIAN', label: '라디오 기술자', classId: 'CLASS_ARTISAN', affinityTags: ['knowledge', 'creativity'], dailyActions: ['진공관과 전선을 점검했습니다', '잡음 속에서 멀리 온 신호를 찾아냈습니다'], signatureObjects: ['납땜 인두', '라디오 수신기'] },
  { id: 'OCC_CIVIL_SERVANT', label: '도시 행정관', classId: 'CLASS_ADMIN', affinityTags: ['stability', 'honor'], dailyActions: ['주민 등록과 배급표를 정리했습니다', '새로운 규정이 시장과 학교에 전달됐는지 확인했습니다'], signatureObjects: ['서류철', '도장'] },
  { id: 'OCC_PHOTOGRAPHER', label: '사진사', classId: 'CLASS_ARTIST', affinityTags: ['creativity', 'connection'], dailyActions: ['빛과 배경을 조절해 사람들의 표정을 담았습니다', '현상한 사진의 날짜와 장소를 기록했습니다'], signatureObjects: ['필름 카메라', '암실 확대기'] },
  { id: 'OCC_PROGRAMMER', label: '초기 컴퓨터 프로그래머', classId: 'CLASS_SCHOLAR', affinityTags: ['knowledge', 'achievement'], dailyActions: ['천공 카드와 명령 순서를 검토했습니다', '반복되는 계산을 더 짧은 절차로 바꾸었습니다'], signatureObjects: ['천공 카드', '자석 테이프'] },
  { id: 'OCC_COMMUNITY_ORGANIZER', label: '지역 공동체 활동가', classId: 'CLASS_COMMON_LABOR', affinityTags: ['connection', 'devotion'], dailyActions: ['주민들의 요구를 모아 회의 안건으로 만들었습니다', '서로 다른 세대가 함께 사용할 공간을 지켰습니다'], signatureObjects: ['회의 수첩', '확성기'] },
  { id: 'OCC_UNEMPLOYED', label: '일자리를 찾는 사람', classId: 'CLASS_COMMON_LABOR', affinityTags: ['survival', 'independence'], dailyActions: ['시장과 공방을 돌며 일자리를 물었습니다', '작은 심부름을 하며 하루를 이어 갔습니다'], signatureObjects: ['구직 쪽지', '작은 가방'] },
  { id: 'OCC_BEGGAR', label: '거리에서 도움을 구한 사람', classId: 'CLASS_COMMON_LABOR', affinityTags: ['survival', 'empathy'], dailyActions: ['사람이 많이 지나는 곳에서 도움을 청했습니다', '받은 음식과 옷을 다른 사람과 나누기도 했습니다'], signatureObjects: ['나무 그릇', '낡은 담요'] },
  { id: 'OCC_CLOWN', label: '광대와 거리 공연자', classId: 'CLASS_ARTIST', affinityTags: ['creativity', 'connection'], dailyActions: ['시장과 축제에서 사람들을 웃게 했습니다', '공연이 끝난 뒤 동료들과 수입을 나누었습니다'], signatureObjects: ['가면', '작은 북'] },
  { id: 'OCC_INDEPENDENCE_FIGHTER', label: '독립운동가', classId: 'CLASS_MILITARY', affinityTags: ['courage', 'devotion'], dailyActions: ['비밀 연락망으로 소식과 물자를 옮겼습니다', '동료의 이름과 약속을 안전하게 보관했습니다'], signatureObjects: ['암호 쪽지', '작은 깃발'] },
  { id: 'OCC_SOLDIER', label: '군인', classId: 'CLASS_MILITARY', affinityTags: ['courage', 'protection'], dailyActions: ['정해진 시간에 초소와 장비를 확인했습니다', '동료와 민간인의 안전한 이동을 도왔습니다'], signatureObjects: ['군번줄', '군용 배낭'] },
  { id: 'OCC_CLEANER', label: '청소부', classId: 'CLASS_COMMON_LABOR', affinityTags: ['stability', 'devotion'], dailyActions: ['사람들이 오기 전 거리와 건물을 정리했습니다', '깨진 물건과 위험한 곳을 먼저 치웠습니다'], signatureObjects: ['빗자루', '양동이'] },
  { id: 'OCC_COOK', label: '요리사', classId: 'CLASS_ARTISAN', affinityTags: ['creativity', 'empathy'], dailyActions: ['남은 재료로 많은 사람이 먹을 음식을 만들었습니다', '불과 물을 아끼며 다음 끼니를 준비했습니다'], signatureObjects: ['국자', '나무 도마'] },
  { id: 'OCC_BAKER', label: '빵 굽는 사람', classId: 'CLASS_ARTISAN', affinityTags: ['stability', 'survival'], dailyActions: ['새벽부터 반죽과 화덕을 살폈습니다', '남은 빵을 필요한 사람에게 나누었습니다'], signatureObjects: ['밀가루 자루', '나무 삽'] },
  { id: 'OCC_BLACKSMITH', label: '대장장이', classId: 'CLASS_ARTISAN', affinityTags: ['creativity', 'survival'], dailyActions: ['불에 달군 쇠를 두드려 도구를 만들었습니다', '농기구와 수레의 부러진 부분을 고쳤습니다'], signatureObjects: ['망치', '모루'] },
  { id: 'OCC_POTTER', label: '도공', classId: 'CLASS_ARTISAN', affinityTags: ['creativity', 'stability'], dailyActions: ['흙을 빚어 그릇과 저장 항아리를 만들었습니다', '가마의 불과 온도를 오래 지켜보았습니다'], signatureObjects: ['물레', '유약 그릇'] },
  { id: 'OCC_DYER', label: '염색공', classId: 'CLASS_ARTISAN', affinityTags: ['creativity', 'achievement'], dailyActions: ['식물과 광물에서 색을 우려냈습니다', '천을 여러 번 씻어 원하는 색을 맞췄습니다'], signatureObjects: ['염색 통', '천 조각'] },
  { id: 'OCC_TAILOR', label: '재봉사', classId: 'CLASS_ARTISAN', affinityTags: ['creativity', 'empathy'], dailyActions: ['사람의 몸에 맞게 옷을 고쳤습니다', '낡은 옷을 풀어 새 옷감으로 다시 만들었습니다'], signatureObjects: ['바늘 상자', '줄자'] },
  { id: 'OCC_COURIER', label: '우편 배달원', classId: 'CLASS_COMMON_LABOR', affinityTags: ['freedom', 'connection'], dailyActions: ['비와 눈에도 편지와 소포를 배달했습니다', '주소가 바뀐 사람을 찾아 우편물을 돌려보냈습니다'], signatureObjects: ['우편 가방', '도장'] },
  { id: 'OCC_DRIVER', label: '마차와 버스 운전사', classId: 'CLASS_COMMON_LABOR', affinityTags: ['adventure', 'connection'], dailyActions: ['정해진 길과 시간을 지키며 사람을 태웠습니다', '길이 막히면 승객에게 다른 길을 설명했습니다'], signatureObjects: ['운전대', '노선표'] },
  { id: 'OCC_RAILWAY_WORKER', label: '철도 노동자', classId: 'CLASS_COMMON_LABOR', affinityTags: ['achievement', 'adventure'], dailyActions: ['선로와 신호를 매일 점검했습니다', '화물과 사람의 이동이 늦어지지 않게 일했습니다'], signatureObjects: ['철도 망치', '신호 깃발'] },
  { id: 'OCC_MINER', label: '광부', classId: 'CLASS_COMMON_LABOR', affinityTags: ['survival', 'courage'], dailyActions: ['어두운 갱도에서 광석을 캐냈습니다', '동료의 램프와 퇴로를 먼저 확인했습니다'], signatureObjects: ['광부 램프', '곡괭이'] },
  { id: 'OCC_LOGGER', label: '벌목꾼', classId: 'CLASS_COMMON_LABOR', affinityTags: ['survival', 'adventure'], dailyActions: ['숲에서 나무를 골라 베었습니다', '강과 길을 따라 목재를 마을로 옮겼습니다'], signatureObjects: ['도끼', '나무 쐐기'] },
  { id: 'OCC_SHEPHERD', label: '목동', classId: 'CLASS_AGRICULTURE', affinityTags: ['calm', 'survival'], dailyActions: ['가축을 물과 풀로 이끌었습니다', '날씨가 나빠지기 전에 안전한 곳을 찾았습니다'], signatureObjects: ['목동 지팡이', '가죽 물통'] },
  { id: 'OCC_BEEKEEPER', label: '양봉가', classId: 'CLASS_AGRICULTURE', affinityTags: ['stability', 'calm'], dailyActions: ['벌통의 상태와 꽃이 피는 시기를 살폈습니다', '꿀을 나누고 벌이 머물 곳을 지켰습니다'], signatureObjects: ['벌통', '연기통'] },
  { id: 'OCC_MIDWIFE', label: '산파', classId: 'CLASS_HEALER', affinityTags: ['empathy', 'protection'], dailyActions: ['아이와 산모의 상태를 차분히 살폈습니다', '가족에게 필요한 돌봄 방법을 알려 주었습니다'], signatureObjects: ['깨끗한 천', '약초 주머니'] },
  { id: 'OCC_HERBALIST', label: '약초꾼', classId: 'CLASS_HEALER', affinityTags: ['knowledge', 'calm'], dailyActions: ['계절에 맞는 약초를 찾아 말렸습니다', '사람마다 맞는 양을 알려 주었습니다'], signatureObjects: ['약초 바구니', '절구'] },
  { id: 'OCC_MUSICIAN', label: '음악가', classId: 'CLASS_ARTIST', affinityTags: ['creativity', 'connection'], dailyActions: ['사람들이 함께 부를 노래를 만들었습니다', '행사와 장례에서 음악으로 마음을 모았습니다'], signatureObjects: ['현악기', '악보'] },
  { id: 'OCC_DANCER', label: '춤꾼', classId: 'CLASS_ARTIST', affinityTags: ['creativity', 'freedom'], dailyActions: ['몸짓으로 이야기와 감정을 전했습니다', '공연 뒤 다음 무대를 위해 연습했습니다'], signatureObjects: ['공연 신발', '색 천'] },
  { id: 'OCC_ACTOR', label: '배우', classId: 'CLASS_ARTIST', affinityTags: ['creativity', 'empathy'], dailyActions: ['다른 사람의 삶을 연습해 무대에 올렸습니다', '관객의 반응을 보고 대사를 다듬었습니다'], signatureObjects: ['대본', '무대 가면'] },
  { id: 'OCC_PRIEST', label: '사제와 성직자', classId: 'CLASS_RELIGIOUS', affinityTags: ['spirituality', 'devotion'], dailyActions: ['공동체의 예배와 의식을 준비했습니다', '슬픔에 빠진 사람의 이야기를 들었습니다'], signatureObjects: ['의례서', '향로'] },
  { id: 'OCC_MONK', label: '수도자', classId: 'CLASS_RELIGIOUS', affinityTags: ['calm', 'knowledge'], dailyActions: ['정해진 시간에 공부와 일을 반복했습니다', '책과 약초를 정리해 다음 사람에게 남겼습니다'], signatureObjects: ['필사본', '나무 그릇'] },
  { id: 'OCC_LAWYER', label: '변호사', classId: 'CLASS_SCHOLAR', affinityTags: ['knowledge', 'honor'], dailyActions: ['사람들의 사정을 듣고 문서를 작성했습니다', '규칙이 약한 사람에게도 적용되는지 따졌습니다'], signatureObjects: ['법률 책', '서류 가방'] },
  { id: 'OCC_TRANSLATOR', label: '통역사', classId: 'CLASS_SCHOLAR', affinityTags: ['knowledge', 'connection'], dailyActions: ['서로 다른 언어의 말을 정확히 옮겼습니다', '오해가 생기면 뜻을 다시 확인했습니다'], signatureObjects: ['두 언어 사전', '통역 수첩'] },
  { id: 'OCC_LIBRARIAN', label: '도서관 사서', classId: 'CLASS_SCHOLAR', affinityTags: ['knowledge', 'stability'], dailyActions: ['책의 위치와 빌린 사람을 기록했습니다', '처음 온 사람에게 필요한 책을 찾아 주었습니다'], signatureObjects: ['대출 카드', '책갈피'] },
  { id: 'OCC_STUDENT', label: '학생', classId: 'CLASS_SCHOLAR', affinityTags: ['knowledge', 'adventure'], dailyActions: ['수업과 일을 함께 하며 배울 시간을 만들었습니다', '친구들과 배운 내용을 서로 설명했습니다'], signatureObjects: ['공책', '연필'] },
  { id: 'OCC_TELEGRAPH_OPERATOR', label: '전신 기사', classId: 'CLASS_ADMIN', affinityTags: ['knowledge', 'connection'], dailyActions: ['짧은 신호를 받아 정확한 문장으로 옮겼습니다', '끊긴 전선을 찾아 소식을 다시 연결했습니다'], signatureObjects: ['전신 키', '전보지'] },
  { id: 'OCC_HARBOR_WORKER', label: '항구 노동자', classId: 'CLASS_COMMON_LABOR', affinityTags: ['adventure', 'survival'], dailyActions: ['배에서 화물을 내리고 싣는 일을 했습니다', '밀물과 날씨를 보며 안전한 순서를 정했습니다'], signatureObjects: ['밧줄', '화물 표'] },
  { id: 'OCC_FISHERMAN', label: '어부', classId: 'CLASS_AGRICULTURE', affinityTags: ['survival', 'adventure'], dailyActions: ['물때와 바람을 보고 바다로 나갔습니다', '잡은 생선을 마을과 시장에 나누었습니다'], signatureObjects: ['그물', '나무 배'] },
  { id: 'OCC_HOUSEKEEPER', label: '집안일을 맡은 사람', classId: 'CLASS_COMMON_LABOR', affinityTags: ['devotion', 'stability'], dailyActions: ['가족이 먹고 쉴 수 있도록 하루를 준비했습니다', '필요한 물건과 남은 식량을 꼼꼼히 살폈습니다'], signatureObjects: ['빨래 방망이', '나무 빗자루'] },
  { id: 'OCC_GARDENER', label: '정원사', classId: 'CLASS_AGRICULTURE', affinityTags: ['calm', 'creativity'], dailyActions: ['계절에 맞는 씨앗과 나무를 돌봤습니다', '사람들이 쉴 그늘과 길을 만들었습니다'], signatureObjects: ['가지치기 가위', '물뿌리개'] },
  { id: 'OCC_WATER_CARRIER', label: '물 나르는 사람', classId: 'CLASS_COMMON_LABOR', affinityTags: ['survival', 'devotion'], dailyActions: ['먼 우물에서 물을 길어 마을로 옮겼습니다', '가족과 이웃의 물 항아리를 채웠습니다'], signatureObjects: ['물동이', '나무 지게'] },
  { id: 'OCC_SALT_WORKER', label: '소금 채취 노동자', classId: 'CLASS_COMMON_LABOR', affinityTags: ['survival', 'stability'], dailyActions: ['바닷물과 햇빛으로 소금을 만들었습니다', '소금 자루를 창고와 시장으로 옮겼습니다'], signatureObjects: ['소금 바구니', '나무 삽'] },
  { id: 'OCC_CARPENTER', label: '목수', classId: 'CLASS_ARTISAN', affinityTags: ['creativity', 'achievement'], dailyActions: ['나무를 재어 집과 가구를 만들었습니다', '낡은 문과 다리를 고쳤습니다'], signatureObjects: ['톱', '먹줄'] },
  { id: 'OCC_GLASSMAKER', label: '유리공', classId: 'CLASS_ARTISAN', affinityTags: ['creativity', 'knowledge'], dailyActions: ['뜨거운 유리를 불어 그릇과 창을 만들었습니다', '깨진 유리 조각을 조심히 골랐습니다'], signatureObjects: ['유리관', '집게'] },
  { id: 'OCC_WATCHMAKER', label: '시계공', classId: 'CLASS_ARTISAN', affinityTags: ['knowledge', 'calm'], dailyActions: ['작은 톱니와 태엽을 맞췄습니다', '사람들의 약속 시간을 다시 맞춰 주었습니다'], signatureObjects: ['돋보기', '시계 부품'] },
  { id: 'OCC_CARTOGRAPHER', label: '지도 제작자', classId: 'CLASS_SCHOLAR', affinityTags: ['knowledge', 'adventure'], dailyActions: ['강과 길의 위치를 측량해 지도에 그렸습니다', '여러 사람의 여행 기록을 비교했습니다'], signatureObjects: ['측량 자', '지도첩'] },
  { id: 'OCC_SURVEYOR', label: '측량사', classId: 'CLASS_SCHOLAR', affinityTags: ['knowledge', 'achievement'], dailyActions: ['땅의 높이와 거리를 재었습니다', '건물과 길을 세울 위치를 정했습니다'], signatureObjects: ['측량 기구', '줄자'] },
  { id: 'OCC_ARCHITECT', label: '건축 설계자', classId: 'CLASS_SCHOLAR', affinityTags: ['creativity', 'achievement'], dailyActions: ['사람이 안전하게 머물 공간을 그렸습니다', '재료와 비용을 맞춰 설계를 고쳤습니다'], signatureObjects: ['설계도', '연필'] },
  { id: 'OCC_BOTANIST', label: '식물 연구자', classId: 'CLASS_SCHOLAR', affinityTags: ['knowledge', 'calm'], dailyActions: ['식물의 모양과 자라는 곳을 기록했습니다', '씨앗과 표본을 다음 계절까지 보관했습니다'], signatureObjects: ['표본첩', '돋보기'] },
  { id: 'OCC_DOCTOR', label: '의사', classId: 'CLASS_HEALER', affinityTags: ['knowledge', 'protection'], dailyActions: ['환자의 말을 듣고 몸의 상태를 살폈습니다', '치료 방법과 쉬는 방법을 설명했습니다'], signatureObjects: ['청진기', '진료 기록'] },
  { id: 'OCC_PARAMEDIC', label: '구급대원', classId: 'CLASS_HEALER', affinityTags: ['courage', 'protection'], dailyActions: ['사고 현장에 가서 다친 사람을 먼저 도왔습니다', '병원까지 안전하게 옮길 방법을 찾았습니다'], signatureObjects: ['구급 상자', '들것'] },
  { id: 'OCC_FIREKEEPER', label: '불을 지키는 사람', classId: 'CLASS_COMMON_LABOR', affinityTags: ['stability', 'protection'], dailyActions: ['공동 화로의 불씨가 꺼지지 않게 돌봤습니다', '불이 번지지 않도록 주변을 정리했습니다'], signatureObjects: ['부지깽이', '물통'] },
  { id: 'OCC_FIRE_FIGHTER', label: '소방관', classId: 'CLASS_MILITARY', affinityTags: ['courage', 'protection'], dailyActions: ['불이 난 곳으로 가서 사람을 대피시켰습니다', '장비와 물길을 확인하며 불을 막았습니다'], signatureObjects: ['소방 호스', '헬멧'] },
  { id: 'OCC_POLICE', label: '경찰관', classId: 'CLASS_MILITARY', affinityTags: ['honor', 'protection'], dailyActions: ['사람들이 안전하게 다닐 길을 지켰습니다', '분실물과 사건의 기록을 남겼습니다'], signatureObjects: ['호루라기', '수첩'] },
  { id: 'OCC_JUDGE', label: '재판관', classId: 'CLASS_ADMIN', affinityTags: ['honor', 'knowledge'], dailyActions: ['서로 다른 사람의 말을 차례로 들었습니다', '기록과 증거를 살펴 결정을 내렸습니다'], signatureObjects: ['판결문', '나무 망치'] },
  { id: 'OCC_TAX_COLLECTOR', label: '세금 징수관', classId: 'CLASS_ADMIN', affinityTags: ['stability', 'honor'], dailyActions: ['마을과 시장의 장부를 확인했습니다', '정해진 세금과 감면 사유를 기록했습니다'], signatureObjects: ['세금 장부', '계산추'] },
  { id: 'OCC_BELL_RINGER', label: '종지기', classId: 'CLASS_RELIGIOUS', affinityTags: ['devotion', 'connection'], dailyActions: ['마을에 시간을 알리는 종을 울렸습니다', '위험과 축제 소식을 사람들에게 전했습니다'], signatureObjects: ['종줄', '시간표'] },
  { id: 'OCC_INNKEEPER', label: '여관 주인', classId: 'CLASS_MERCHANT', affinityTags: ['connection', 'stability'], dailyActions: ['여행객에게 잠자리와 따뜻한 음식을 내주었습니다', '떠난 사람의 소식과 길 상태를 기억했습니다'], signatureObjects: ['객실 장부', '열쇠 꾸러미'] },
] as const;

const retiredOccupationIds = new Set(['OCC_01', 'OCC_02', 'OCC_03', 'OCC_04', 'OCC_05', 'OCC_06', 'OCC_07', 'OCC_08']);
export const historicalOccupations: readonly HistoricalOccupation[] = allHistoricalOccupations.filter(({ id }) => !retiredOccupationIds.has(id));
